# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AltunaGroup' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AltunaGroup

  # pod 'SideMenu', '~> 2.3.4'
  pod 'SideMenu'

  # pod 'Alamofire', '~> 4.7'
  pod 'Alamofire', '~> 5.0.0-beta.2'

  pod 'SwiftyJSON', '~> 4.0'
  
  # pod 'Kingfisher', '~> 4.0.0'
  pod 'Kingfisher', '~> 5.0'

  pod ‘SCLAlertView’
  
  # pod 'NewPopMenu', '~> 1.1'
  pod 'NewPopMenu'

end
